
let days : Day.t list =
  [
    new Day00.t;
    (* new day1; *)
    (* new day2; *)
    (* new day3; *)
    (* new day4; *)
    (* new day5; *)
    (* new day6; *)
    (* new day7; *)
    (* new day8; *)
    (* new day9; *)
    (* new day11; *)
    (* new day11; *)
    (* new day12; *)
    (* new day13; *)
    (* new day14; *)
    (* new day15; *)
    (* new day16; *)
    (* new day17; *)
    (* new day18; *)
    (* new day19; *)
    (* new day20; *)
    (* new day21; *)
    (* new day22; *)
    (* new day23; *)
    (* new day24; *)
    (* new day25 *)
  ]
