name: Builds, tests & co

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

env:
  OCAML_COMPILER_VER: "5.1"

jobs:
  ci:
    runs-on: [linux]
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ env.OCAML_COMPILER_VER }}

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
